planner:
  alias: planner
  openai_api_key: YourOpenAIAPIKey
  openai_base_url: YourOpenAIBaseURL
  model: gpt-4o # 貌似gpt-4o-mini无法有效遵循json schema prompt进行输出
  model_kwargs:
    temperature: 0.8
  embedding_model: YourEmbeddingModel
  cases_path: src/cases/plans
  max_workers: 10
  workspace_path: src/workspaces/test

code_interpreter:
  alias: code_interpreter
  openai_api_key: YourOpenAIAPIKey
  openai_base_url: YourOpenAIBaseURL
  model: gpt-4o # 貌似gpt-4o-mini无法有效遵循json schema prompt进行输出
  model_kwargs:
    temperature: 0.8
  embedding_model: YourEmbeddingModel
  cases_path: src/cases/codes
  max_workers: 10
  workspace_path: src/workspaces/test
  notebook_name: execution_log.ipynb